// <auto-generated />
using AngelsManagement.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngelsManagement.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20180624163716_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("AngelsManagement.Model.Guardian", b =>
                {
                    b.Property<long>("GuardianId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("GuardianId");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("AngelsManagement.Model.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("BirthYear");

                    b.Property<string>("City");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("School");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AngelsManagement.Model.StuPar", b =>
                {
                    b.Property<long>("StudentId");

                    b.Property<long>("GuardianId");

                    b.HasKey("StudentId", "GuardianId");

                    b.HasIndex("GuardianId");

                    b.ToTable("StuPar");
                });

            modelBuilder.Entity("AngelsManagement.Model.VolStu", b =>
                {
                    b.Property<long>("VolunteerId");

                    b.Property<long>("StudentId");

                    b.HasKey("VolunteerId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("VolStu");
                });

            modelBuilder.Entity("AngelsManagement.Model.Volunteer", b =>
                {
                    b.Property<long>("VolunteerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<long>("BirthYear");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("VolunteerId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("AngelsManagement.Model.StuPar", b =>
                {
                    b.HasOne("AngelsManagement.Model.Guardian", "Guardian")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AngelsManagement.Model.Student", "Student")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AngelsManagement.Model.VolStu", b =>
                {
                    b.HasOne("AngelsManagement.Model.Student", "Student")
                        .WithMany("VolunteerStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AngelsManagement.Model.Volunteer", "Volunteer")
                        .WithMany("VolunteerStudents")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
