// <auto-generated />
using AngelsManagement.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngelsManagement.Migrations.Users
{
    [DbContext(typeof(UsersContext))]
    [Migration("20180927091817_InitialCreateUsers")]
    partial class InitialCreateUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("AngelsManagement.Model.UserCredentials", b =>
                {
                    b.Property<long>("UserCredentialsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HashedPassword");

                    b.Property<string>("Login");

                    b.Property<string>("Salt");

                    b.HasKey("UserCredentialsId");

                    b.ToTable("UserCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
